#!/usr/bin/env bash
# This script is used for testing the docker image specified in Dockerfile.

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

main() {
  # Generate an SSH key which will be used both by the server (which is running as an
  # unprivileged user and hence has no access to the root user keys), and by the
  # client.
  ssh-keygen -t ed25519 -C '' -N '' -f ~/.ssh/id_ed25519
  cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys
  # Start sshd and et servers to test ssh-et
  /usr/sbin/sshd -h ~/.ssh/id_ed25519
  nohup etserver &
  ~/ssh-et "$@"
}

main "$@"
